import Foundation
import AirlineEmpireCore

/// Prints the audio manifest as Markdown, straight from `AudioCue`.
///
/// `docs/AUDIO_ASSET_MANIFEST.md` §3 is generated by this rather than typed, so the
/// documented category, priority and cooldown of a sound cannot drift from the
/// ones the game actually uses. Run:
///
///     swift run ae-audio-manifest
print("| Cue | Asset | Category | Priority | Cooldown | Haptic |")
print("| --- | --- | --- | --- | --- | --- |")
for cue in AudioCue.allCases.sorted(by: { $0.rawValue < $1.rawValue }) {
    let cooldown = cue.cooldown == 0 ? "—" : String(format: "%.2fs", cue.cooldown)
    let milestone = cue.isMilestone ? " ·  first-time" : ""
    let haptic = cue.haptic.map(\.rawValue) ?? "—"
    print("| `\(cue.rawValue)`\(milestone) | `\(cue.assetName).wav` "
          + "| \(cue.category.rawValue) | \(cue.priority) | \(cooldown) "
          + "| \(haptic) |")
}
